#!/usr/bin/env python3
"""Download ALTTPR .zspr sprites into the local library folder `sprites/`.

The library index is `sprites/library.json` (a copy of the ALTTPR sprite
index, reference copy lives at ../reference/alttpr_sprites.json relative to
the repo root). Sprites are stored under their URL file name, e.g.
    https://alttpr-assets.s3.us-east-2.amazonaws.com/meatwad.2.zspr
    -> sprites/meatwad.2.zspr
which is exactly the path src/sprites.c resolves `name=<...>` to.

Usage (from the repo root or anywhere):
  python tools/fetch_sprites.py                 # default set (Meatwad + 3 more)
  python tools/fetch_sprites.py Meatwad         # just Meatwad
  python tools/fetch_sprites.py "Sonic 3" Kirby # names are matched against
                                                # library.json (fuzzy)
  python tools/fetch_sprites.py --all           # the whole library (513 files),
                                                # resumable: already-present
                                                # files are skipped

Every run (re)generates `sprites/sprite_library.ini`, the catalog the
in-game sprite cycler reads (F11 next / Shift+F11 previous, src/sprites.c):
    sprite=<display name>|<file name relative to sprites/>
It lists the FULL library, not just what is downloaded - the engine skips
missing/corrupt files, so partially-downloaded libraries cycle fine.

Name matching is case-insensitive and ignores non-alphanumerics, same rule
the engine uses. The S3 bucket is public; plain urllib, no auth.
"""
import json
import os
import shutil
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)                      # repo root (zelda3/)
SPRITES_DIR = os.path.join(BASE, "sprites")
LIBRARY = os.path.join(SPRITES_DIR, "library.json")
CATALOG = os.path.join(SPRITES_DIR, "sprite_library.ini")

# Fallback locations for the reference index copy, in order.
REFERENCE_LIBRARY_CANDIDATES = [
    os.path.join(os.path.dirname(BASE), "reference", "alttpr_sprites.json"),
    os.path.join(BASE, "other", "alttpr_sprites.json"),
]

# Default set: Meatwad (the house pick) plus three visually distinctive ones.
DEFAULT_SPRITES = ["Meatwad", "Pikachu", "Kirby", "Batman"]

USER_AGENT = "zelda3-stream-build-fetch-sprites/1.0"


def ensure_library():
    """Return the parsed library index, copying the reference json in if the
    local copy does not exist yet."""
    if not os.path.exists(LIBRARY):
        for cand in REFERENCE_LIBRARY_CANDIDATES:
            if os.path.exists(cand):
                os.makedirs(SPRITES_DIR, exist_ok=True)
                shutil.copyfile(cand, LIBRARY)
                print("library: copied %s -> %s" %
                      (os.path.relpath(cand, BASE), os.path.relpath(LIBRARY, BASE)))
                break
        else:
            sys.exit("ERROR: sprites/library.json missing and no reference "
                     "alttpr_sprites.json found (looked in %s)" %
                     ", ".join(REFERENCE_LIBRARY_CANDIDATES))
    with open(LIBRARY, "r", encoding="utf-8") as fh:
        return json.load(fh)


def norm(s):
    return "".join(c.lower() for c in s if c.isalnum())


def find_entry(library, name):
    key = norm(name)
    for e in library:
        if norm(e.get("name", "")) == key:
            return e
    return None


def write_catalog(library):
    """Write sprites/sprite_library.ini for the in-game cycler. One line per
    unique sprite, in library.json order; deduped by normalized name (the
    engine resolves picks by name, so duplicate names would be unreachable).
    Written BEFORE any downloading so a partially fetched library already
    cycles (the engine skips missing files)."""
    seen = set()
    lines = [
        "# Generated by tools/fetch_sprites.py from sprites/library.json - do not hand-edit.",
        "# Format: sprite=<display name>|<file name relative to sprites/>",
    ]
    count = 0
    for e in library:
        name = " ".join(str(e.get("name", "")).split()) or ""
        base = str(e.get("file", "")).rsplit("/", 1)[-1].strip()
        key = norm(name)
        if not key or not base or key in seen:
            continue
        seen.add(key)
        lines.append("sprite=%s|%s" % (name.replace("|", "/"), base))
        count += 1
    os.makedirs(SPRITES_DIR, exist_ok=True)
    with open(CATALOG, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("catalog: wrote %s (%d sprites)" %
          (os.path.relpath(CATALOG, BASE), count))
    return count


def fetch(entry):
    """Download one sprite. Returns the path when fetched, None when it was
    already present (resumable). Raises on network/format errors so the
    caller can count the failure and keep going."""
    url = entry["file"]
    out = os.path.join(SPRITES_DIR, url.rsplit("/", 1)[-1])
    if os.path.exists(out) and os.path.getsize(out) > 1000:
        print("have    %-28s (%s)" % (entry["name"], os.path.basename(out)))
        return None
    os.makedirs(SPRITES_DIR, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:
        data = resp.read()
    if not data.startswith(b"ZSPR"):
        raise ValueError("%s did not download a .zspr file (got %d bytes)" %
                         (url, len(data)))
    with open(out, "wb") as fh:
        fh.write(data)
    print("fetched %-28s -> %s (%.1f KB)" %
          (entry["name"], os.path.relpath(out, BASE), len(data) / 1024.0))
    return out


def fetch_all(library):
    """Fetch every library sprite, resumable/skip-existing, never aborting on
    a single failure. Prints and returns ok/failed/skipped counts."""
    print("fetching all %d library sprites into %s/ (skip-existing) ..." %
          (len(library), os.path.relpath(SPRITES_DIR, BASE)))
    ok = failed = skipped = 0
    for entry in library:
        try:
            if fetch(entry) is None:
                skipped += 1
            else:
                ok += 1
        except Exception as exc:  # one bad file must not stop the batch
            failed += 1
            print("ERROR: %s: %s" % (entry.get("name", "?"), exc))
    print("\ndownload stats: ok=%d skipped(already present)=%d failed=%d" %
          (ok, skipped, failed))
    return ok, failed, skipped


def main(argv):
    names = []
    do_all = False
    for a in argv[1:]:
        if a == "--all":
            do_all = True
        else:
            names.append(a)
    library = ensure_library()
    write_catalog(library)
    rc = 0
    if do_all:
        ok, failed, _skipped = fetch_all(library)
        if failed:
            rc = 1
    else:
        if not names:
            names = DEFAULT_SPRITES
        for name in names:
            entry = find_entry(library, name)
            if entry is None:
                print("ERROR: no library entry matching %r" % name)
                rc = 1
                continue
            try:
                fetch(entry)
            except Exception as exc:
                print("ERROR: %s" % exc)
                rc = 1
                continue
            print("        sprites.ini line:  name=%s" % entry["name"])
        print("\ndone. enable with a sprites.ini in the repo root containing e.g.:")
        print("  name=Meatwad")
        print("or press F11 in game (Shift+F11 = previous) to cycle sprites/sprite_library.ini.")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv))
