#!/usr/bin/env python3
"""Regenerate src/rando_tables.inc for the phase-B randomizer (src/randomizer.c).

Emits two static tables:
  kForkChestRoomWords[168] - the US 1.0 ROM chest table at PC 0xE96E, room
      words in ROM scan order (bit15 = big chest).  The engine asset
      kDungeonRoomChests holds the same records re-sorted by room; the fork's
      location addresses (PC offsets 0xE96E..0xEB65) index the ROM order.
  kRandoItemCodes[] - ALTTPR item name -> ROM item value (= the engine chest
      byte), lifted from the ALttPDoorRandomizer fork's Items.py item_table
      (185 entries).  Codes >= 0x4C (76) have no engine receipt slot and are
      refused by the boot-time apply; dungeon keys/maps/compasses are mapped
      to the vanilla native codes by a prefix rule in randomizer.c instead.

Usage (repo root): python tools/gen_rando_tables.py
"""
import json
import sys

ROM = 'zelda3.sfc'
CHEST_BASE = 0xE96E
CHEST_BYTES = 504
ITEM_CODES_JSON = 'randomizer_ref/_item_codes.json'
OUT = 'src/rando_tables.inc'


def main():
    rom = open(ROM, 'rb').read()
    words = [rom[CHEST_BASE + i] | (rom[CHEST_BASE + i + 1] << 8)
             for i in range(0, CHEST_BYTES, 3)]
    assert len(words) == 168

    lines = []
    for i in range(0, 168, 8):
        lines.append('  ' + ' '.join('0x%04x,' % w for w in words[i:i + 8]))
    room_table = ('/* generated by tools/gen_rando_tables.py - do not edit */\n'
                  'static const uint16 kForkChestRoomWords[168] = {\n'
                  + '\n'.join(lines) + '\n};\n')

    codes = json.load(open(ITEM_CODES_JSON))
    items = sorted(codes.items(), key=lambda kv: kv[0].lower())
    rows = ['  { "%s", 0x%02x },' % (name.replace('"', '\\"'), int(code, 16))
            for name, code in items]
    item_table = (
        '/* ALTTPR item name -> ROM item value (the engine chest byte), from the\n'
        ' * fork\'s Items.py item_table.  Values >= 0x4C (76) have no engine receipt\n'
        ' * slot (kReceiveItemAlternates & friends are 76-entry tables) and are\n'
        ' * refused by ApplyFillPlacements. */\n'
        'typedef struct { const char *name; uint16 code; } RandoItemCode;\n'
        'static const RandoItemCode kRandoItemCodes[] = {\n' + '\n'.join(rows) + '\n};\n')

    open(OUT, 'w').write(room_table + '\n' + item_table)
    print('wrote %s: %d room words, %d item codes'
          % (OUT, len(words), len(items)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
